# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mainwindow(object):
    def setupUi(self, Mainwindow):
        Mainwindow.setObjectName("Mainwindow")
        Mainwindow.resize(710, 540)
        Mainwindow.setStyleSheet("")
        self.background = QtWidgets.QLabel(Mainwindow)
        self.background.setGeometry(QtCore.QRect(0, 0, 710, 540))
        self.background.setStyleSheet("background-color: rgb(40, 44, 52);\n"
"border-radius:10px")
        self.background.setText("")
        self.background.setObjectName("background")
        self.splitter = QtWidgets.QSplitter(Mainwindow)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 710, 540))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.titles = QtWidgets.QWidget(self.splitter)
        self.titles.setMaximumSize(QtCore.QSize(16777215, 40))
        self.titles.setObjectName("titles")
        self.titleTool = QtWidgets.QWidget(self.titles)
        self.titleTool.setGeometry(QtCore.QRect(600, 0, 111, 41))
        self.titleTool.setStyleSheet("background-color:transparent;\n"
"")
        self.titleTool.setObjectName("titleTool")
        self.layoutWidget = QtWidgets.QWidget(self.titleTool)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 96, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.small = QtWidgets.QToolButton(self.layoutWidget)
        self.small.setStyleSheet("::hover{\n"
"    background-color:#fff;\n"
"}")
        self.small.setObjectName("small")
        self.horizontalLayout_6.addWidget(self.small)
        self.exit = QtWidgets.QToolButton(self.layoutWidget)
        self.exit.setStyleSheet("::hover{\n"
"    background-color:rgb(255, 0, 0);\n"
"}")
        self.exit.setObjectName("exit")
        self.horizontalLayout_6.addWidget(self.exit)
        self.title = QtWidgets.QTextBrowser(self.titles)
        self.title.setGeometry(QtCore.QRect(0, 15, 611, 21))
        self.title.setStyleSheet("background-color: transparent;\n"
"border:none;")
        self.title.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.title.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.title.setOverwriteMode(True)
        self.title.setAcceptRichText(True)
        self.title.setObjectName("title")
        self.mainStack = QtWidgets.QStackedWidget(self.splitter)
        self.mainStack.setStyleSheet("QTextBrowser{\n"
"    background-color: transparent;\n"
"    border:none;\n"
"}")
        self.mainStack.setObjectName("mainStack")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.splitter_2 = QtWidgets.QSplitter(self.page)
        self.splitter_2.setGeometry(QtCore.QRect(0, 0, 711, 461))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(3)
        self.splitter_2.setObjectName("splitter_2")
        self.welcome_title = QtWidgets.QTextBrowser(self.splitter_2)
        self.welcome_title.setObjectName("welcome_title")
        self.image = QtWidgets.QLabel(self.splitter_2)
        self.image.setMinimumSize(QtCore.QSize(300, 0))
        self.image.setText("")
        self.image.setObjectName("image")
        self.mainStack.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 691, 471))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.info_install = QtWidgets.QTextBrowser(self.layoutWidget1)
        self.info_install.setMinimumSize(QtCore.QSize(0, 0))
        self.info_install.setObjectName("info_install")
        self.verticalLayout.addWidget(self.info_install)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 40, 671, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(17)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.path = QtWidgets.QLineEdit(self.layoutWidget2)
        self.path.setObjectName("path")
        self.horizontalLayout_4.addWidget(self.path)
        self.browser = QtWidgets.QPushButton(self.layoutWidget2)
        self.browser.setStyleSheet("color: rgb(0, 0, 0);")
        self.browser.setObjectName("browser")
        self.horizontalLayout_4.addWidget(self.browser)
        self.verticalLayout.addWidget(self.groupBox)
        self.size_group = QtWidgets.QTextBrowser(self.layoutWidget1)
        self.size_group.setObjectName("size_group")
        self.verticalLayout.addWidget(self.size_group)
        self.mainStack.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.layoutWidget3 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(2, 2, 711, 451))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TheAgreement = QtWidgets.QTextBrowser(self.layoutWidget3)
        self.TheAgreement.setObjectName("TheAgreement")
        self.verticalLayout_2.addWidget(self.TheAgreement)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.agreeAgreement = QtWidgets.QCheckBox(self.layoutWidget3)
        self.agreeAgreement.setObjectName("agreeAgreement")
        self.horizontalLayout_5.addWidget(self.agreeAgreement)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.mainStack.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.all_info = QtWidgets.QTextBrowser(self.page_4)
        self.all_info.setGeometry(QtCore.QRect(0, 0, 711, 451))
        self.all_info.setObjectName("all_info")
        self.mainStack.addWidget(self.page_4)
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_2.setStyleSheet("color:#000")
        self.widget_2.setObjectName("widget_2")
        self.layoutWidget4 = QtWidgets.QWidget(self.widget_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 1, 711, 32))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Language = QtWidgets.QLabel(self.layoutWidget4)
        self.Language.setStyleSheet("color:#fff;")
        self.Language.setObjectName("Language")
        self.horizontalLayout.addWidget(self.Language)
        self.Language_Choose = QtWidgets.QComboBox(self.layoutWidget4)
        self.Language_Choose.setObjectName("Language_Choose")
        self.horizontalLayout.addWidget(self.Language_Choose)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.Back = QtWidgets.QPushButton(self.layoutWidget4)
        self.Back.setEnabled(True)
        self.Back.setObjectName("Back")
        self.horizontalLayout_3.addWidget(self.Back)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Next = QtWidgets.QPushButton(self.layoutWidget4)
        self.Next.setObjectName("Next")
        self.horizontalLayout_2.addWidget(self.Next)
        self.Install = QtWidgets.QPushButton(self.layoutWidget4)
        self.Install.setObjectName("Install")
        self.horizontalLayout_2.addWidget(self.Install)
        self.Cancel = QtWidgets.QPushButton(self.layoutWidget4)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_2.addWidget(self.Cancel)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Mainwindow)
        self.mainStack.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Mainwindow)

    def retranslateUi(self, Mainwindow):
        _translate = QtCore.QCoreApplication.translate
        Mainwindow.setWindowTitle(_translate("Mainwindow", "Form"))
        self.small.setText(_translate("Mainwindow", "➖"))
        self.exit.setText(_translate("Mainwindow", "❌"))
        self.title.setHtml(_translate("Mainwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono ExtraBold\'; font-weight:80;\">Welcome to install {appName}!</span></p></body></html>"))
        self.welcome_title.setHtml(_translate("Mainwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono ExtraBold\'; font-size:12pt; font-weight:80;\">Welcome to the {appName} installer, this program is a very good one</span></p></body></html>"))
        self.info_install.setHtml(_translate("Mainwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono ExtraBold\'; font-size:12pt; font-weight:80;\">We will install {appName} in the following directory, please double-check and start the installation</span></p></body></html>"))
        self.groupBox.setTitle(_translate("Mainwindow", "Destination Folder"))
        self.path.setText(_translate("Mainwindow", "D:\\"))
        self.browser.setText(_translate("Mainwindow", "Browse.."))
        self.size_group.setHtml(_translate("Mainwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.TheAgreement.setHtml(_translate("Mainwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono ExtraBold\'; font-weight:80;\">Hello Wolrd!<br /></span></p></body></html>"))
        self.agreeAgreement.setText(_translate("Mainwindow", "I agree to this agreement"))
        self.all_info.setHtml(_translate("Mainwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono ExtraBold\'; font-size:16pt; font-weight:80;\">Installation location：</span><span style=\" font-family:\'JetBrains Mono ExtraBold\'; font-size:16pt; font-weight:80; font-style:italic;\">{path}</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono ExtraBold\'; font-size:16pt; font-weight:80;\">Software name：</span><span style=\" font-family:\'JetBrains Mono ExtraBold\'; font-size:16pt; font-weight:80; font-style:italic;\">{appName}</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'JetBrains Mono ExtraBold\'; font-size:16pt; font-weight:80;\"><br /></p></body></html>"))
        self.Language.setText(_translate("Mainwindow", "Language:"))
        self.Back.setText(_translate("Mainwindow", "Back"))
        self.Next.setText(_translate("Mainwindow", "Next"))
        self.Install.setText(_translate("Mainwindow", "安装"))
        self.Cancel.setText(_translate("Mainwindow", "Cancel"))
import main_rc
